# Generated by Django 5.0.1 on 2026-02-04 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_id'),
        ('mappings', '0001_initial'),
        ('patients', '0002_alter_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDoctorMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, help_text='When assignment was made')),
                ('notes', models.TextField(blank=True, help_text='Special notes about this assignment', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this assignment currently active')),
                ('doctor', models.ForeignKey(help_text='Doctor assigned to patient', on_delete=django.db.models.deletion.CASCADE, related_name='patient_mappings', to='doctors.doctor')),
                ('patient', models.ForeignKey(help_text='Patient in this mapping', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_mappings', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient-Doctor Mapping',
                'verbose_name_plural': 'Patient-Doctor Mappings',
                'ordering': ['-assigned_date'],
                'unique_together': {('patient', 'doctor')},
            },
        ),
        migrations.DeleteModel(
            name='PatiendDoctorMapping',
        ),
    ]
