# Generated by Django 6.0.1 on 2026-02-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('CARDIOLOGY', 'Cardiology'), ('NEUROLOGY', 'Neurology'), ('PEDIATRICS', 'Pediatrics'), ('ORTHOPEDICS', 'Orthopedics'), ('DERMATOLOGY', 'Dermatology'), ('GENERAL', 'General Physician')], max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('experience_years', models.IntegerField()),
                ('qualification', models.CharField(max_length=255)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
