# Generated by Django 6.0.1 on 2026-02-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available',
            field=models.BooleanField(default=True, help_text='Currently available for patients'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience_years',
            field=models.IntegerField(help_text='Years of experience'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(help_text='MBBS, MD, etc.', max_length=255),
        ),
    ]
